name: Run dependabot for cake
on:
  workflow_dispatch:

jobs:
  dependabot-cake:
    runs-on: ubuntu-latest # linux, because this is a docker-action
    steps:
      - name: check/update cake dependencies
        uses: nils-org/dependabot-cake-action@c3da34d3dbf9b35d0319e3b861c2935b7c56757a