name: Run dependabot for cake
on:
  workflow_dispatch:

jobs:
  dependabot-cake:
    runs-on: ubuntu-latest # linux, because this is a docker-action
    steps:
      - name: check/update cake dependencies
        uses: nils-org/dependabot-cake-action@v1.1.0
        with:
          ignore: |
            Cake.7zip
            Cake.asciidoctorj
            Cake.FileHelpers
