name: Run dependabot for cake
on:
  workflow_dispatch:

jobs:
  dependabot-cake:
    runs-on: ubuntu-latest # linux, because this is a docker-action
    steps:
      - name: check/update cake dependencies
        uses: nils-org/dependabot-cake-action@b5eafa78fe47bc6575fbbe4601d5fd694db8abb7
        with:
          ignore: |
            Cake.7zip
            Cake.asciidoctorj
            Cake.FileHelpers
